### ISSUE TITLE
hrvana interpolate nan values limit issue

### ISSUE THREAD

**Issue by csuustc** [bzhai/multimodal_sleep_stage_benchmark#1]
Hi there,

I'm executing the align_actigraphy_rri.py. You did really great job!

```
clean_rri = hrv_df['RR Intervals'].values
clean_rri = hrvana.remove_outliers(rr_intervals=clean_rri, low_rri=300, high_rri=2000)
clean_rri = hrvana.interpolate_nan_values(rr_intervals=clean_rri, interpolation_method="linear")
clean_rri = hrvana.remove_ectopic_beats(rr_intervals=clean_rri, method="malik")
clean_rri = hrvana.interpolate_nan_values(rr_intervals=clean_rri, interpolation_method="linear")
```
I guess there is a problem that `hrvana.interpolate_nan_values` can only fill 1 value by default limit=1, so some continuous ectopic R-R intervals could only be filled 1 value and leave others as NA. That why the following "processed frequency domain features" got so many Exceptions. Do you think it'd be better to drop the NA lines or fill all NA lines?

**Comment by bzhai** [comment]
Hi,
Yes, there is a problem in function : `hrvana.interpolate_nan_values`. I think it would be worth to fill these NA values to reduce the "Exceptions".

**Comment by csuustc** [comment]
Thanks for your reply!

By the way, another question, I'm interested in the LSTM model and I saw in the appendix you said 3 layers can get a better result. But I tried to build the LSTM model for Task3, and added 2 LSTM layers, but the no improvement.

So what does it mean by 3 layers? Are they all LSTM layers or just some Dense layer? And what's the accuracy rate for 3 layers?

Thank you so much.

**Comment by bzhai** [comment]
Your results similar to my observation from the experiment, I found some numerical improvement on accuracy. However, these improvements aren't statistically significant (95% CI). These results you can find in 5.2. 
For LSTM models they are LSTM networks, not the dense layers. I also uploaded the hyper-parameter tuning results into the `results` folder. 
All the best. 
Bing

**Comment by csuustc** [comment]
Thanks for your explanation!
